[tasks.stencil]
description = "Re-run stencil"
run = "stencil --skip-update"
depends_post = "post-stencil"

[tasks.post-stencil]
description = "Discover and run tasks meant to be run after stencil completes (prefixed with 'post-stencil:')"
run = """{{ mise_bin }} run $({{ mise_bin }} tasks ls --json | gojq --raw-output '. | map(select(.name | startswith("post-stencil:")).name) | join(" ::: ")')"""

[tasks."post-stencil:circleci-orb-sync"]
description = "Sync CircleCI orb version with devbase version"
run = "./scripts/shell-wrapper.sh circleci-orb-sync.sh"
